_target_: comde.comde_modules.seq2seq.SkillToSkillMLP
seed: ${seed}
cfg:
  inseq_dim: ${skill_dim} # Input sequence = sequence of skills
  dropout: 0.0
  activation_fn: relu
  net_arch:
    - 128
    - 128
    - 128
    - 128

  lr: 1e-4
  max_source_skills: 4
  coef_skill_loss: 1.0
  skill_dim: ${skill_dim}
