_target_: comde.comde_modules.seq2seq.SkillCompositionTransformer

seed: ${seed}

cfg:
  inseq_dim: ${skill_dim} # Input sequence = sequence of skills
  lr: 1e-4
  startend_token_path: /home/jsw7460/mnt/comde_datasets/language_embeddings/bert_mappings/tokens/bert_base_start_end_tokens
  skill_pred_type: discrete
  save_suffix: ${save_suffix}
  encoder_max_len: ${max_source_skills}
  decoder_max_len: ${max_target_skills}

  transformer_cfg:
    input_dropout_prob: 0.1

    encoder_cfg:
      num_layers: 1
      input_dim: ${language_dim}
      num_heads: 4
      ff_dim: 8
      dropout_prob: 0.1
      use_bias: True
      max_len: ${max_source_skills}
      activation_fn: relu

    decoder_cfg:
      num_layers: 1
      input_dim: ${language_dim}
      num_heads: 4
      ff_dim: 8
      dropout_prob: 0.1
      use_bias: True
      max_len: ${max_target_skills}
      activation_fn: relu
