path: comde.rl.envs.franka_kitchen.franka_kitchen.FrankaKitchen

# What tasks you evaluate
eval_tasks_path: /home/jsw7460/mnt/comde_datasets/tasks_for_evals/kitchen/idx_eval-9

# Prediction of Semantic skill encoder: Dict [Task -> Predicted skills sequence]
source_skills_path: /home/jsw7460/mnt/comde_datasets/source_skills/kitchen/optimal_four_skills
template_path: /home/jsw7460/mnt/comde_datasets/language_embeddings/bert_mappings/language_guidance/BERT_kitchen_templates

task_video_path: /home/jsw7460/mnt/comde_datasets/videos/kitchen/task_video_embeddings

timelimit: 350
termination_pred_interval: 9
n_target: 4
language_operators:
  sequential:
    - do these sequentially
    - please follow this in order

  parallel:
    - x
    - y

  parameterized:
    - x
    - y
