seed: 777

defaults:
  - low_policy: skill_dt
  - seq2seq: mlp
  - intent_emb: vq
  - termination: mlp
  - wandb: comde_train
  - env: metaworld
  - mode: comde

save_prefix: /home/andykim0723/comde_save/train2/
save_suffix: foo
modules: ${mode.modules}
trainer: ${mode.trainer}

act_scale: 1.05
observation_dim: ${env.observation_dim}
action_dim: ${env.action_dim}
dataset_path: /home/andykim0723/comde_datasets/v0.0.1/

skill_dim: 512
intent_dim: ${mode.intent_dim}
subseq_len: 20
batch_size: 1024
max_iter: 500
step_per_dataset: 5000
log_interval: 1000
language_guidance_path: /home/andykim0723/comde_datasets/language_guidance/sequential_clip_mapping
