seed: 777

defaults:
  - low_policy: skill_dt
  - seq2seq: transformer
#  - intent_emb: vq
  - termination: mlp
  - wandb: comde_train
  - env: metaworld
  - mode: comde
  - dataset: base
  - baseline: retail

save_prefix: /home/jsw7460/comde_save/train/
save_suffix: foo
modules: ${mode.modules}
trainer: ${mode.trainer}
non_functionality_dim: ${language_dim}
param_dim: 10

act_scale: 1.35
observation_dim: ${env.observation_dim}
action_dim: ${env.action_dim}
dataset_path: ???

max_source_skills: 6
max_target_skills: 6

state_normalization: False
skill_dim: ${language_dim} # 512 for clip, 1024 for bert.
language_dim: 1024
subseq_len: 5
batch_size: 256
max_iter: 500
step_per_dataset: 5000
log_interval: 1000
sequential_requirements_path: ${env.sequential_requirements_path}
non_functionalities_path: ${env.non_functionalities_path}
