seed: 777

defaults:
  - low_policy: skill_dt
  - seq2seq: transformer
  - intent_emb: vq
  - termination: mlp
  - wandb: comde_train
  - env: metaworld
  - mode: comde
  - dataset: base

save_prefix: /home/jsw7460/comde_save/train/
save_suffix: foo
modules: ${mode.modules}
trainer: ${mode.trainer}

act_scale: 1.05
observation_dim: ${env.observation_dim}
action_dim: ${env.action_dim}
dataset_path: ???

max_source_skills: 3
max_target_skills: 3

skill_dim: 512
intent_dim: ${mode.intent_dim}
subseq_len: 5
batch_size: 1024
max_iter: 500
step_per_dataset: 5000
log_interval: 1000
language_guidance_path: /home/jsw7460/mnt/comde_datasets/clip_mappings/language_guidance/sequential_clip_mapping
