seed: 777

#env: metaworld
defaults:
  - low_policy: skill_mlp
  - seq2seq: transformer
#  - intent_emb: vq
  - termination: mlp
  - wandb: comde_train
  - env: kitchen
  - mode: comde
  - dataset: base
  - baseline: flatbc
  - prompt_learner: transformer
  - translate_learner: transformer
  - language_space: bert
  - sensor_encoder: transformer

save_prefix: /home/jsw7460/comde_save/train/
save_suffix: foo
modules: ${mode.modules}
trainer: ${mode.trainer}
non_functionality_dim: ${language_dim}

act_scale: ${env.act_scale}
observation_dim: ${env.observation_dim}
action_dim: ${env.action_dim}
dataset_path: ???

max_source_skills: 7
max_target_skills: 7

state_normalization: False
skill_dim: ${language_dim}
update_seq2seq: False

# language_dim: CLIP: 512 / Bert-base: 768 / Bert-large: 1024
language_dim: ${language_space.language_dim}
subseq_len: 5
batch_size: 256
max_iter: 500
dataset_window_size: 2500
step_per_dataset: ${mode.step_per_dataset}
log_interval: 100
save_interval: ${mode.save_interval}
#skill_infos_path: ${env.skill_infos_path}
#sequential_requirements_path: ${env.sequential_requirements_path}
#non_functionalities_path: ${env.non_functionalities_path}
datadir_limit: ${mode.datadir_limit}
excluded_dirs:
  - videofeature_mapping
  - firstimage_mapping
  - firstimage_mapping_vit