#low_policy:
_target_: comde.comde_modules.low_policies.SkillDecisionTransformer
seed: ${seed}
cfg:
  gpt2_config:
    vocab_size: 1
    n_positions: 1024
    n_layer: 4
    n_head: 8
    activation_function: gelu_new
    resid_pdrop: 0.1
    embd_pdropo: 0.1
    attn_pdrop: 0.1
    layer_norm_epsilon: 0

  hidden_size: 64
  act_scale: ${act_scale}
  subseq_len: ${subseq_len}
  lr: 1e-4
  max_ep_len: 1024

  observation_dim: ${observation_dim}
  action_dim: ${action_dim}
  skill_dim: ${skill_dim}
