_target_: comde.baselines.VLPromptDT
seed: ${seed}
cfg:
  obs_mean: 0.0
  obs_std: 1.0

  dt_cfg:
    gpt2_config:
      vocab_size: 1 # Does not matter
      n_positions: 1024
      n_layer: 3
      n_head: 4
      resid_pdrop: 0.1
      embd_pdrop: 0.1
      attn_pdrop: 0.1
    obs_dim: ${observation_dim}
    act_dim: ${action_dim}
    only_prompt: True
    hidden_size: 64
    act_scale: ${act_scale}
    max_ep_len: 1024

  language_dim: ${language_dim}
  observation_dim: ${observation_dim}
  action_dim: ${action_dim}
  skill_dim: ${skill_dim}
  sequential_requirements_dim: ${language_dim}
  non_functionality_dim: ${non_functionality_dim}
  param_dim: ${env.param_dim}
  param_repeats: ${env.param_repeats}
  act_scale: ${act_scale}
  prompt_dim: 768

  firstimage_path: ${env.firstimage_path}

  conditioning_mode: ???  # skill / task
  skill_video_path: ${env.skill_video_path}
  task_video_path: ${env.task_video_path}
  n_target_skill: ${env.n_target_skill}

  n_source_video: 1
  lr: 1e-4

  policy_cfg:
    output_dim: ${action_dim}
    net_arch:
      - 256
      - 256
      - 256
      - 256
      - 256
    activation_fn: relu
    dropout: 0.0
    squash_output: True
    layer_norm: False