defaults:
  - env: metaworld

seed: 0
pretrained_prefix: /home/jsw7460/comde_save/train
date: 2023-04-11  # yyyy-mm-dd. Date for trained model
pretrained_suffix: ???
step: 120000

pretrained_path: ${pretrained_prefix}/${date}/cfg/cfg_${pretrained_suffix}
sequential_requirement: sequential
non_functionality: wind

use_optimal_target_skill: False
use_optimal_next_skill: False

save_results: False
save_prefix: /home/jsw7460/comde_save/eval
save_suffix: foo
