defaults:
  - env: metaworld

seed: 0
n_eval: 3
pretrained_prefix: /home/jsw7460/comde_save/train
date: 2023-05-13  # yyyy-mm-dd. Date for trained model
pretrained_suffix: ???
step: 500000

pretrained_path: ${pretrained_prefix}/${date}/cfg/cfg_${pretrained_suffix}
sequential_requirement: sequential
non_functionality: ???

use_optimal_target_skill: True
use_optimal_next_skill: False

save_text: False
save_results: False
save_prefix: /home/jsw7460/comde_save/eval
text_save_prefix: /home/jsw7460/comde/comde_eval/
save_suffix: eval
termination_pred_interval: ${env.termination_pred_interval}

# Define pretrained models (Skill composition and prompting)
composition: /home/jsw7460/comde_save/train/2023-06-20/seq2seq/compose_mtktrlb_50000.zip
prompt: /home/jsw7460/comde_save/train/2023-06-20/prompt_learner/prompt_mtktrlb_24000.zip
