defaults:
  - env: metaworld

seed: 0
pretrained_prefix: /home/andykim0723/comde_save/train
date: 2023-03-19  # yyyy-mm-dd. Date for trained model
pretrained_suffix: foo

pretrained_path: ${pretrained_prefix}/${date}/cfg/cfg_${pretrained_suffix}
language_guidance: sequential

save_results: True
save_prefix: /home/andykim0723/comde_save/eval