defaults:
  - env: metaworld

seed: 0
pretrained_prefix: /home/jsw7460/comde_save/train
date: 2023-03-28  # yyyy-mm-dd. Date for trained model
pretrained_suffix: ???

pretrained_path: ${pretrained_prefix}/${date}/cfg/cfg_${pretrained_suffix}
language_guidance: sequential

use_optimal_next_skill: False

save_results: False
save_prefix: /home/jsw7460/comde_save/eval
save_suffix: foo
