defaults:
  - env: metaworld

seed: 0
n_eval: 3
pretrained_prefix: /home/jsw7460/comde_save/train
date: 2023-05-13  # yyyy-mm-dd. Date for trained model
pretrained_suffix: ???
step: 500000

pretrained_path: ${pretrained_prefix}/${date}/cfg/cfg_${pretrained_suffix}
sequential_requirement: sequential
non_functionality: ???
parameter: default

use_optimal_target_skill: False
use_optimal_next_skill: False

save_text: False
save_results: False
save_prefix: /home/jsw7460/comde_save/eval
text_save_prefix: /home/jsw7460/comde/comde_eval/
save_suffix: eval
termination_pred_interval: ${env.termination_pred_interval}

# Define pretrained models (Skill composition and prompting)
composition: /home/jsw7460/comde_save/train/2023-07-03/seq2seq/bert_translation_50000.zip
prompt: /home/jsw7460/comde_save/train/2023-07-02/prompt_learner/bert_incontext_60000.zip

#composition: /home/jsw7460/comde_save/train/2023-07-05/seq2seq/t5_translation_105000.zip
#prompt: /home/jsw7460/comde_save/train/2023-07-03/prompt_learner/t5_incontext_104100.zip
